"""Medical-disclaimer + no-health-claims enforcement: the AI response post-processor (AIA-505).

"As the company, AI output is disclaimed and makes no health claims." Sanitizing input
(:mod:`app.guardrails.sanitizer`) and screening unsafe output (:mod:`app.guardrails.policy`) keep
the service safe; this last guard keeps it *compliant*. :class:`ResponsePostProcessor` is the single
deterministic post-processor both AI use cases run before returning, and it does two things:

* **Disclaim every response (AC1).** :meth:`ResponsePostProcessor.disclaimer` returns a localized
  notice ("...generated by AI...not medical advice...consult a professional") that the
  recommendation and analysis responses carry as metadata, so AI output is never presented as
  clinical guidance.
* **Strip diagnostic/medical claims (AC2).** :meth:`ResponsePostProcessor.scrub` removes any
  sentence of generated free-text (a recommendation's reasoning, a recipe's description/steps) that
  reads like a health claim -- curing/treating/preventing a condition, a diagnosis, a
  clinical-authority boast, or a physiological-effect claim -- and records it through a
  :class:`MedicalClaimTelemetry` port.

Both checks are intentionally tight and condition-anchored (es + en) so ordinary food language
("healthy breakfast", "high in protein", "desayuno saludable") is never touched: :meth:`scrub`
returns benign text *verbatim*. Everything here is pure -- no LLM, no I/O -- so it is fully
unit-testable, and it backs the AIA-506 adversarial guardrail suite.
"""

from __future__ import annotations

import logging
import re
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from enum import StrEnum
from typing import Protocol, runtime_checkable

from app.prompts.types import Locale

_LOGGER = logging.getLogger("app.guardrails.compliance")
_DEFAULT_LOCALE = Locale.default()


class MedicalClaimCategory(StrEnum):
    """Why a sentence of generated text was removed as a health claim."""

    DIAGNOSIS = "diagnosis"
    TREATMENT = "treatment"
    PREVENTION = "prevention"
    AUTHORITY = "authority"
    EFFECT = "effect"


@dataclass(frozen=True, slots=True)
class MedicalClaimEvent:
    """A single removed claim: the field it came from and the category that fired."""

    source: str
    category: MedicalClaimCategory


@runtime_checkable
class MedicalClaimTelemetry(Protocol):
    """A write port: record that the post-processor removed a medical claim from output."""

    def record(self, event: MedicalClaimEvent) -> None: ...


class InMemoryMedicalClaimTelemetry:
    """Collects events in a list so tests can assert what was removed and counted."""

    def __init__(self) -> None:
        self.events: list[MedicalClaimEvent] = []

    def record(self, event: MedicalClaimEvent) -> None:
        self.events.append(event)

    @property
    def count(self) -> int:
        """Total number of recorded claim removals."""
        return len(self.events)

    def count_for(self, category: MedicalClaimCategory) -> int:
        """How many recorded removals were of ``category``."""
        return sum(1 for event in self.events if event.category is category)

    @property
    def categories(self) -> list[MedicalClaimCategory]:
        """The category of each recorded removal, in record order."""
        return [event.category for event in self.events]


class LoggingMedicalClaimTelemetry:
    """Emits one WARNING per removed claim -- a stripped health claim is worth noting."""

    def __init__(self, logger: logging.Logger | None = None) -> None:
        self._logger = logger or _LOGGER

    def record(self, event: MedicalClaimEvent) -> None:
        self._logger.warning(
            "medical claim removed from output: category=%s source=%s",
            event.category.value,
            event.source or "?",
        )


# The localized disclaimer attached to every AI response (AC1). Plain, non-clinical wording.
_DISCLAIMERS: Mapping[Locale, str] = {
    Locale.EN: (
        "This information is AI-generated for general wellness and is not medical advice. "
        "Consult a qualified healthcare professional before making dietary or health decisions."
    ),
    Locale.ES: (
        "Esta información es generada por IA con fines de bienestar general y no constituye "
        "consejo médico. Consulta a un profesional de la salud cualificado antes de tomar "
        "decisiones dietéticas o de salud."
    ),
}


# --- Claim-detection patterns --------------------------------------------------------------------
# Tight and condition-anchored by design: a benign recipe/reasoning string must never trip these.
# Each is paired with the category it represents; a matching sentence is removed from the output.

# Conditions a claim is allowed to reference (en + es). A claim verb alone is never enough.
_CONDITION = (
    r"(?:disease|diseases|illness|illnesses|condition|conditions|disorder|disorders|cancer|"
    r"diabetes|diabetic|hypertension|cholesterol|obesity|arthritis|asthma|depression|anxiety|"
    r"inflammation|infections?|covid|flu|influenza|insomnia|migraines?|"
    r"enfermedad(?:es)?|cáncer|hipertensión|colesterol|obesidad|artritis|asma|"
    r"depresión|ansiedad|inflamación|infección|infecciones|gripe|insomnio)"
)

_TREATMENT = re.compile(
    r"(?:"
    r"\b(?:cure[sd]?|curing|heals?|healed|healing|reverse[sd]?|reversing|treat(?:s|ed|ing)?)\b\s+"
    r"(?:your\s+|the\s+|an?\s+|chronic\s+|any\s+)?"
    + _CONDITION
    + r"|\b(?:treatment|cure|remedy)\s+for\s+(?:your\s+|the\s+|an?\s+|chronic\s+)?"
    + _CONDITION
    + r"|\b(?:cura[rn]?|curan|sana[rn]?|revierten?|revertir|trata[rn]?|tratan)\b\s+"
    r"(?:tu\s+|el\s+|la\s+|los\s+|las\s+|una?\s+)?" + _CONDITION + r")",
    re.IGNORECASE,
)

_PREVENTION = re.compile(
    r"(?:"
    r"\b(?:prevent(?:s|ed|ing)?|protects?\s+against|protecting\s+against|wards?\s+off)\b\s+"
    r"(?:your\s+|the\s+|an?\s+|chronic\s+|any\s+)?"
    + _CONDITION
    + r"|\b(?:previene[n]?|prevenir|protege[n]?\s+contra)\b\s+"
    r"(?:tu\s+|el\s+|la\s+|los\s+|las\s+|una?\s+)?" + _CONDITION + r")",
    re.IGNORECASE,
)

_DIAGNOSIS = re.compile(
    r"\bdiagnos(?:e[sd]?|ing|is|es)\b|\bdiagnóstic[ao]s?\b|\bdiagnostica[rn]?\b",
    re.IGNORECASE,
)

_AUTHORITY = re.compile(
    r"\b(?:clinically|medically|scientifically)\s+(?:proven|tested|shown|validated)\b"
    r"|\bdoctor[-\s]?recommended\b|\bfda[-\s]?approved\b"
    r"|\bclínicamente\s+(?:probado|comprobado|demostrado)\b"
    r"|\baprobado\s+por\s+la\s+fda\b|\brecomendado\s+por\s+médicos\b",
    re.IGNORECASE,
)

_EFFECT = re.compile(
    r"\b(?:lowers?|lowering|reduces?|reducing|cuts?|cutting)\b\s+"
    r"(?:your\s+|the\s+)?(?:blood\s+pressure|blood\s+sugar|blood\s+glucose|cholesterol)"
    r"|\bboosts?\s+(?:your\s+)?immune\s+system\b"
    r"|\bdetox(?:if(?:y|ies|ying))?\s+(?:your\s+)?(?:body|liver|blood)\b"
    r"|\b(?:baja|bajan|bajar|reduce[n]?|reducir)\s+"
    r"(?:tu\s+|el\s+|la\s+)?(?:colesterol|presión\s+arterial|azúcar\s+en\s+sangre)"
    r"|\brefuerza[n]?\s+(?:tu\s+)?sistema\s+inmune\b",
    re.IGNORECASE,
)

_PATTERNS: tuple[tuple[re.Pattern[str], MedicalClaimCategory], ...] = (
    (_DIAGNOSIS, MedicalClaimCategory.DIAGNOSIS),
    (_TREATMENT, MedicalClaimCategory.TREATMENT),
    (_PREVENTION, MedicalClaimCategory.PREVENTION),
    (_AUTHORITY, MedicalClaimCategory.AUTHORITY),
    (_EFFECT, MedicalClaimCategory.EFFECT),
)

# Stable order in which fired categories are recorded, regardless of detection order.
_RECORD_ORDER: tuple[MedicalClaimCategory, ...] = (
    MedicalClaimCategory.DIAGNOSIS,
    MedicalClaimCategory.TREATMENT,
    MedicalClaimCategory.PREVENTION,
    MedicalClaimCategory.AUTHORITY,
    MedicalClaimCategory.EFFECT,
)

# Split on sentence terminators, keeping the terminator with the sentence it ends.
_SENTENCE_SPLIT = re.compile(r"(?<=[.!?])\s+")
_WHITESPACE = re.compile(r"\s+")


def _claim_categories(sentence: str) -> set[MedicalClaimCategory]:
    """Every claim category a single sentence trips (empty set means it is clean)."""
    return {category for pattern, category in _PATTERNS if pattern.search(sentence)}


class ResponsePostProcessor:
    """Disclaim AI responses and strip diagnostic/medical claims from their generated free-text."""

    def __init__(
        self,
        telemetry: MedicalClaimTelemetry | None = None,
        *,
        disclaimers: Mapping[Locale, str] = _DISCLAIMERS,
    ) -> None:
        self._telemetry = telemetry or LoggingMedicalClaimTelemetry()
        self._disclaimers = disclaimers

    def disclaimer(self, locale: Locale | str = _DEFAULT_LOCALE) -> str:
        """Return the localized disclaimer to attach to a response (AC1)."""
        resolved = Locale.parse(locale, default=_DEFAULT_LOCALE)
        return self._disclaimers.get(resolved, self._disclaimers[_DEFAULT_LOCALE])

    def scrub(self, text: str, *, source: str = "") -> str:
        """Return ``text`` with any health-claim sentence removed, recording each category fired.

        Benign text is returned **verbatim** (no claim found short-circuits), so ordinary recipe and
        reasoning language is never reshaped.
        """
        sentences = _SENTENCE_SPLIT.split(text.strip())
        fired: set[MedicalClaimCategory] = set()
        kept: list[str] = []
        for sentence in sentences:
            categories = _claim_categories(sentence)
            if categories:
                fired |= categories
            elif sentence:
                kept.append(sentence)
        if not fired:
            return text
        for category in _RECORD_ORDER:
            if category in fired:
                self._telemetry.record(MedicalClaimEvent(source=source, category=category))
        return _WHITESPACE.sub(" ", " ".join(kept)).strip()

    def scrub_optional(self, text: str | None, *, source: str = "") -> str | None:
        """Scrub an optional field, collapsing to ``None`` when nothing survives."""
        if text is None:
            return None
        scrubbed = self.scrub(text, source=source)
        return scrubbed or None

    def scrub_each(self, values: Iterable[str], *, source: str = "") -> tuple[str, ...]:
        """Scrub each value (e.g. recipe steps), dropping any left empty by claim removal."""
        scrubbed = (self.scrub(value, source=source) for value in values)
        return tuple(value for value in scrubbed if value)
